spring.application.name=liquorApp
spring.datasource.url=jdbc:postgresql://localhost:5432/my_springboot_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update